twitch:
  clientId: ""
  accessToken: ""
  channels:
    - jordofthenorth
    - timthetatman
    - dam0un
    - surdaft

image:
  repository: damoun/twitch-exporter
  pullPolicy: Always
  tag: "latest@sha256:733ab88ecec8b0fdbf24e80af2a16e434d5d3c0d0cbe65577d7ee38c07c43ee0"

serviceAccount:
  create: true
  automount: true

service:
  type: ClusterIP
  port: 9184

ingress:
  enabled: false

resources: {}