twitch:
  # client-id is required at all times
  clientId: ""

  # client secret is preferred for use without private data, as it uses no oauth
  # flow to grant access to the API. Endpoints such as sub counts are not with
  # this method.
  #
  # if both client-secret and access-token are provided, client-secret will be
  # used.
  clientSecret: ""

  # access-token & refresh-token are required for use with private data, such
  # as sub counts.
  accessToken: ""
  refreshToken: ""

  # channels is a list of channels to export metrics for.
  channels:
    - jordofthenorth
    - timthetatman
    - dam0un
    - surdaft

image:
  repository: damoun/twitch-exporter
  pullPolicy: Always
  tag: "latest"

  # pullSecrets is a list of secrets to use for pulling the image.
  pullSecrets: []
  # pullSecrets:
  #   - name: dockerhub
  #     namespace: default

serviceAccount:
  create: true
  automount: true

service:
  type: ClusterIP
  port: 9184

ingress:
  enabled: false

resources: {}

podLabels: {}

podAnnotations: {}

volumes: []
volumeMounts: []
