apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "twitch_exporter.fullname" . }}
  labels:
    {{- include "twitch_exporter.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "twitch_exporter.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "twitch_exporter.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- if .Values.image.pullSecrets }}
      imagePullSecrets:
        {{- toYaml .Values.image.pullSecrets | nindent 8 }}
      {{- end }}

      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}

          args: [
            {{- if .Values.twitch.accessToken }}
            # access token is provided as a secret
            "--twitch.access-token=$(TWITCH_ACCESS_TOKEN)",
            {{- end -}}

            {{- if .Values.twitch.refreshToken }}
            # refresh token is provided as a secret
            "--twitch.refresh-token=$(TWITCH_REFRESH_TOKEN)",
            {{- end -}}

            {{- if .Values.twitch.clientId }}
            # client id is provided as a secret
            "--twitch.client-id=$(TWITCH_CLIENT_ID)",
            {{- end -}}

            {{- if .Values.twitch.clientSecret }}
            # client secret is provided as a secret
            "--twitch.client-secret=$(TWITCH_CLIENT_SECRET)",
            {{- end -}}

            {{- range .Values.twitch.channels }}
            "--twitch.channel={{ . }}",
            {{- end }}
          ]
          envFrom:
            - secretRef:
                name: twitch-exporter-env
          {{- if .Values.volumeMounts }}
          volumeMounts:
            {{- toYaml .Values.volumeMounts | nindent 12 }}
          {{- end }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: {{ .Values.service.port }}
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
        {{- if .Values.volumes }}
        volumes:
          {{- toYaml .Values.volumes | nindent 12 }}
        {{- end }}