apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "twitch_exporter.fullname" . }}
  labels:
    {{- include "twitch_exporter.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "twitch_exporter.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "twitch_exporter.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}

          args: [
            {{- if .Values.twitch.accessToken }}
            # access token is provided as a secret
            "--twitch.access-token=$(TWITCH_ACCESS_TOKEN)",
            {{ end -}}

            {{- if .Values.twitch.refreshToken }}
            # refresh token is provided as a secret
            "--twitch.refresh-token=$(TWITCH_REFRESH_TOKEN)",
            {{ end -}}

            {{- if .Values.twitch.clientSecret }}
            # client secret is provided as a secret
            "--twitch.client-secret=$(TWITCH_CLIENT_SECRET)",
            {{ end -}}

            # config is provided as a config map
            "--config=/var/secrets/config.yml"
          ]
          envFrom:
            - secretRef:
                name: twitch-exporter-env
          volumeMounts:
            - name: twitch-exporter-config
              mountPath: /var/secrets
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: {{ .Values.service.port }}
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      volumes:
        - name: twitch-exporter-config
          configMap:
            name: twitch-exporter-config