{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "twitch_exporter.fullname" . }}
  labels:
    {{- include "twitch_exporter.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "twitch_exporter.selectorLabels" . | nindent 6 }}
  policyTypes:
    - Ingress
    {{- if .Values.networkPolicy.egress.enabled }}
    - Egress
    {{- end }}
  ingress:
    - ports:
        - port: {{ .Values.service.port }}
          protocol: TCP
      {{- if or .Values.networkPolicy.ingressFrom .Values.networkPolicy.allowNamespaces }}
      from:
        {{- range .Values.networkPolicy.allowNamespaces }}
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: {{ . }}
        {{- end }}
        {{- with .Values.networkPolicy.ingressFrom }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- end }}
  {{- if .Values.networkPolicy.egress.enabled }}
  egress:
    {{- with .Values.networkPolicy.egress.rules }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- end }}
{{- end }}
