{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "twitch_exporter.fullname" . }}
  labels:
    {{- include "twitch_exporter.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "twitch_exporter.selectorLabels" . | nindent 6 }}
  policyTypes:
    - Ingress
  ingress:
    - ports:
        - port: {{ .Values.service.port }}
          protocol: TCP
{{- end }}
