apiVersion: v1
kind: Secret
metadata:
  name: twitch-exporter-env
type: Opaque
stringData:
  TWITCH_ACCESS_TOKEN: "{{ .Values.twitch.accessToken }}"
  TWITCH_REFRESH_TOKEN: "{{ .Values.twitch.refreshToken }}"

  TWITCH_CLIENT_SECRET: "{{ .Values.twitch.clientSecret }}"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: twitch-exporter-config
data:
  config.yml: |
    twitch:
      clientId: "{{ .Values.twitch.clientId }}"
      channels:
        {{- toYaml .Values.twitch.channels | nindent 8 }}
