{{- if not .Values.twitch.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "twitch_exporter.secretName" . }}
  labels:
    {{- include "twitch_exporter.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- if .Values.twitch.clientId }}
  TWITCH_CLIENT_ID: "{{ .Values.twitch.clientId }}"
  {{- end }}
  {{- if .Values.twitch.clientSecret }}
  TWITCH_CLIENT_SECRET: "{{ .Values.twitch.clientSecret }}"
  {{- end }}
  {{- if .Values.twitch.accessToken }}
  TWITCH_ACCESS_TOKEN: "{{ .Values.twitch.accessToken }}"
  {{- end }}
  {{- if .Values.twitch.refreshToken }}
  TWITCH_REFRESH_TOKEN: "{{ .Values.twitch.refreshToken }}"
  {{- end }}
  {{- if .Values.twitch.eventsub.enabled }}
  EVENTSUB_WEBHOOK_URL: "{{ .Values.twitch.eventsub.webhookURL }}"
  EVENTSUB_WEBHOOK_SECRET: "{{ .Values.twitch.eventsub.webhookSecret }}"
  {{- end }}
{{- end }}
