apiVersion: v1
kind: Secret
metadata:
  name: twitch-exporter-env
type: Opaque
stringData:
  TWITCH_CLIENT_ID: "{{ .Values.twitch.clientId }}"
  TWITCH_ACCESS_TOKEN: "{{ .Values.twitch.accessToken }}"
