// Much of this file has been referenced from:
// https://github.com/prometheus/node_exporter/blob/master/collector/collector.go

package collector

import (
	"errors"
	"fmt"
	"log/slog"
	"sync"
	"time"

	"github.com/alecthomas/kingpin/v2"
	"github.com/damoun/twitch_exporter/config"
	"github.com/nicklaw5/helix/v2"
	"github.com/prometheus/client_golang/prometheus"
	"github.com/prometheus/client_golang/prometheus/promauto"
)

const namespace = "twitch"

var (
	scrapeDurationDesc = prometheus.NewDesc(
		prometheus.BuildFQName(namespace, "scrape", "collector_duration_seconds"),
		"Duration of a collector scrape.",
		[]string{"collector"},
		nil,
	)
	scrapeSuccessDesc = prometheus.NewDesc(
		prometheus.BuildFQName(namespace, "scrape", "collector_success"),
		"Whether a collector succeeded.",
		[]string{"collector"},
		nil,
	)

	accessTokenRefreshed = promauto.NewCounter(prometheus.CounterOpts{
		Namespace: namespace,
		Subsystem: "twitch",
		Name:      "access_token_refresh_count",
		Help:      "Counter of access token refreshes",
	})
)

const (
	defaultEnabled  = true
	defaultDisabled = false
)

var (
	factories              = make(map[string]func(logger *slog.Logger, client *helix.Client, cfg *config.Config) (Collector, error))
	initiatedCollectorsMtx = sync.Mutex{}
	initiatedCollectors    = make(map[string]Collector)
	collectorState         = make(map[string]*bool)
	forcedCollectors       = map[string]bool{} // collectors which have been explicitly enabled or disabled
)

func registerCollector(collector string, isDefaultEnabled bool, factory func(logger *slog.Logger, client *helix.Client, cfg *config.Config) (Collector, error)) {
	var helpDefaultState string
	if isDefaultEnabled {
		helpDefaultState = "enabled"
	} else {
		helpDefaultState = "disabled"
	}

	flagName := "collector." + collector
	flagHelp := fmt.Sprintf("Enable the %s collector (default: %s).", collector, helpDefaultState)
	defaultValue := fmt.Sprintf("%v", isDefaultEnabled)

	flag := kingpin.Flag(flagName, flagHelp).Default(defaultValue).Action(collectorFlagAction(collector)).Bool()
	collectorState[collector] = flag

	factories[collector] = factory
}

type Exporter struct {
	Collectors map[string]Collector
	filters    []string
	sc         *config.SafeConfig

	logger *slog.Logger
}

// Describe describes all the metrics ever exported by the Twitch exporter. It
// implements prometheus.Collector.
func (e *Exporter) Describe(ch chan<- *prometheus.Desc) {
	ch <- scrapeDurationDesc
	ch <- scrapeSuccessDesc
}

func DisableDefaultCollectors() {
	for c := range collectorState {
		if _, ok := forcedCollectors[c]; !ok {
			*collectorState[c] = false
		}
	}
}

// collectorFlagAction generates a new action function for the given collector
// to track whether it has been explicitly enabled or disabled from the command line.
// A new action function is needed for each collector flag because the ParseContext
// does not contain information about which flag called the action.
// See: https://github.com/alecthomas/kingpin/issues/294
func collectorFlagAction(collector string) func(ctx *kingpin.ParseContext) error {
	return func(ctx *kingpin.ParseContext) error {
		forcedCollectors[collector] = true
		return nil
	}
}

func populateFilter(filters []string) (map[string]bool, error) {
	f := make(map[string]bool)
	for _, filter := range filters {
		enabled, exist := collectorState[filter]
		if !exist {
			return nil, fmt.Errorf("missing collector: %s", filter)
		}

		if !*enabled {
			return nil, fmt.Errorf("disabled collector: %s", filter)
		}
		f[filter] = true
	}

	return f, nil
}

func NewExporter(logger *slog.Logger, sc *config.SafeConfig, filters ...string) (*Exporter, error) {
	e := &Exporter{
		filters: filters,
		sc:      sc,
		logger:  logger,
	}

	if err := e.Reload(); err != nil {
		return nil, err
	}

	return e, nil
}

func (e *Exporter) Reload() error {
	initiatedCollectors = make(map[string]Collector)

	e.sc.Lock()
	conf := e.sc.C
	e.sc.Unlock()

	opts := &helix.Options{
		ClientID: conf.Twitch.ClientID,
	}

	if conf.Twitch.ClientSecret != "" {
		opts.ClientSecret = conf.Twitch.ClientSecret
	}

	// assume the token given is a user token, since an app token
	// is just generated by the app
	if conf.Twitch.AccessToken != "" {
		opts.UserAccessToken = conf.Twitch.AccessToken
	}

	client, err := helix.NewClient(opts)

	if err != nil {
		e.logger.Error("could not initialise twitch client", "err", err.Error())
		return err
	}

	if conf.Twitch.ClientSecret != "" && conf.Twitch.AccessToken == "" {
		go func() {
			refresh := time.NewTicker(time.Hour * 24)
			for range refresh.C {
				resp, err := client.RequestAppAccessToken([]string{})
				if err != nil {
					e.logger.Error("could not request app access token", "err", err.Error())
				}

				client.SetAppAccessToken(resp.Data.AccessToken)
				accessTokenRefreshed.Inc()
			}
		}()
	}

	f, err := populateFilter(e.filters)
	if err != nil {
		return err
	}

	collectors := make(map[string]Collector)
	initiatedCollectorsMtx.Lock()
	defer initiatedCollectorsMtx.Unlock()
	for key, enabled := range collectorState {
		if !*enabled || (len(f) > 0 && !f[key]) {
			continue
		}
		if collector, ok := initiatedCollectors[key]; ok {
			collectors[key] = collector
		} else {
			collector, err := factories[key](e.logger, client, conf)
			if err != nil {
				return err
			}

			collectors[key] = collector
			initiatedCollectors[key] = collector
		}
	}

	e.Collectors = collectors
	return nil
}

func (e *Exporter) Collect(ch chan<- prometheus.Metric) {
	wg := sync.WaitGroup{}
	wg.Add(len(e.Collectors))
	for name, c := range e.Collectors {
		go func(name string, c Collector) {
			execute(name, c, ch, e.logger)
			wg.Done()
		}(name, c)
	}
	wg.Wait()
}

func execute(name string, c Collector, ch chan<- prometheus.Metric, logger *slog.Logger) {
	begin := time.Now()
	err := c.Update(ch)
	duration := time.Since(begin)
	var success float64

	attrs := []any{
		"name", name,
		"duration_seconds", duration.Seconds(),
	}

	if err != nil {
		if IsNoDataError(err) {
			logger.Debug("collector returned no data", attrs...)
		} else {
			attrs = append(attrs, "err", err.Error())
			logger.Error("collector failed", attrs...)
		}
		success = 0
	} else {
		logger.Debug("collector succeeded", attrs...)
		success = 1
	}

	ch <- prometheus.MustNewConstMetric(scrapeDurationDesc, prometheus.GaugeValue, duration.Seconds(), name)
	ch <- prometheus.MustNewConstMetric(scrapeSuccessDesc, prometheus.GaugeValue, success, name)
}

// Collector is the interface a collector has to implement.
type Collector interface {
	// Get new metrics and expose them via prometheus registry.
	Update(ch chan<- prometheus.Metric) error
}

type typedDesc struct {
	desc      *prometheus.Desc
	valueType prometheus.ValueType
}

func (d *typedDesc) mustNewConstMetric(value float64, labels ...string) prometheus.Metric {
	return prometheus.MustNewConstMetric(d.desc, d.valueType, value, labels...)
}

var ErrNoData = errors.New("collector returned no data")

func IsNoDataError(err error) bool {
	return err == ErrNoData
}
