---
name: Build
on:
  pull_request:
    branches:
      - main

jobs:
  docker:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false
      - uses: docker/setup-buildx-action@4d04d5d9486b7bd6fa91e7baf45bbb4f8b9deedd # v4.0.0
      - run: docker buildx build --platform linux/amd64 --load -t twitch-exporter:test .
      - run: docker run twitch-exporter:test --help
