---
name: Build
on:
  pull_request:
    branches:
      - main

jobs:
  golang:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.6
      - uses: actions/setup-go@0a12ed9d6a96ab950c8f026ed9f722fe0da7ef32 # v5
        with:
          go-version: '^1.22.2'
      - run: make promu
      - run: promu crossbuild -v
      - name: Store binaries
        uses: actions/upload-artifact@0b2256b8c012f0828dc542b3febcab082c67f72b # v4.3.4
        with:
          name: build
          path: .build
      - name: Test binary
        run: .build/linux-amd64/twitch_exporter --help

  docker:
    needs: golang
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.6
      - name: Download binaries artifacts
        uses: actions/download-artifact@fa0a91b85d4f404e444e00e005971372dc801d16 # v4
        with:
          name: build
          path: .build
      # See https://github.com/actions/upload-artifact/issues/38
      - name: Fix permission on binaries artifacts
        run: find . -type f -name 'twitch_exporter' -exec chmod +x {} +
      - run: make docker
      - run: docker run docker.io/damoun/twitch-exporter-linux-amd64:HEAD --help
