name: Helm Validate

on:
  push:
    paths:
      - "charts/**"
  pull_request:
    paths:
      - "charts/**"

permissions:
  contents: read

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - uses: azure/setup-helm@dda3372f752e03dde6b3237bc9431cdc2f7a02a2 # v5.0.0

      - name: Helm lint
        run: helm lint charts/twitch-exporter/

      - name: Helm template dry-run
        run: helm template test charts/twitch-exporter/ --set twitch.clientId=test --set twitch.clientSecret=test
