name: Helm Validate

on:
  push:
    paths:
      - "charts/**"
  pull_request:
    paths:
      - "charts/**"

permissions:
  contents: read

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - uses: azure/setup-helm@9bc31f4ebc9c6b171d7bfbaa5d006ae7abdb4310 # v5.0.1

      - name: Helm lint
        run: helm lint charts/twitch-exporter/

      - name: Helm template dry-run
        run: helm template test charts/twitch-exporter/ --set twitch.clientId=test --set twitch.clientSecret=test
