---
name: Publish
on:
  push:
    branches:
      - main
  release:
    types:
      - created

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.6
      - uses: actions/setup-go@v5
        with:
          go-version: '^1.22.2'
      - run: make promu
      - run: promu crossbuild -v
      - name: Store binaries artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: .build

  publish:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.6
      - name: Download binaries artifacts
        uses: actions/download-artifact@v4
        with:
          name: build
          path: .build
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - run: make docker DOCKER_IMAGE_TAG="${{ github.ref_name }}"
      - run: make docker-publish DOCKER_IMAGE_TAG="${{ github.ref_name }}"
      - run: make docker-manifest DOCKER_IMAGE_TAG="${{ github.ref_name }}"
      - if: startsWith(github.ref, 'refs/tags/v')
        run: |
          make docker-tag-latest DOCKER_IMAGE_TAG="${{ github.ref_name }}"
          make docker-publish DOCKER_IMAGE_TAG="latest"
          make docker-manifest DOCKER_IMAGE_TAG="latest"
