---
name: Publish
on:
  push:
    branches:
      - main
  release:
    types:
      - created

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      - uses: actions/setup-go@f111f3307d8850f501ac008e886eec1fd1932a34 # v5.3.0
        with:
          go-version: '^1.22.2'
      - run: make promu
      - run: promu crossbuild -v
      - name: Store binaries artifacts
        uses: actions/upload-artifact@65c4c4a1ddee5b72f698fdd19549f0f0fb45cf08 # v4.6.0
        with:
          name: build
          path: .build
          if-no-files-found: error
      - name: Test binary
        run: .build/linux-amd64/twitch_exporter --help

  publish:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      - name: Download binaries artifacts
        uses: actions/download-artifact@fa0a91b85d4f404e444e00e005971372dc801d16 # v4.1.8
        with:
          name: build
          path: .build
      # See https://github.com/actions/upload-artifact/issues/38
      - name: Fix permission on binaries artifacts
        run: find . -type f -name 'twitch_exporter' -exec chmod +x {} +
      - name: Login to Docker Hub
        uses: docker/login-action@9780b0c442fbb1117ed29e0efdff1e18412f7567 # v3.3.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - run: make docker DOCKER_IMAGE_TAG="${{ github.ref_name }}"
      - run: make docker-publish DOCKER_IMAGE_TAG="${{ github.ref_name }}"
      - run: make docker-manifest DOCKER_IMAGE_TAG="${{ github.ref_name }}"
      - if: startsWith(github.ref, 'refs/tags/v')
        run: |
          make docker-tag-latest DOCKER_IMAGE_TAG="${{ github.ref_name }}"
          make docker-publish DOCKER_IMAGE_TAG="latest"
          make docker-manifest DOCKER_IMAGE_TAG="latest"
      - run: docker run docker.io/damoun/twitch-exporter-linux-amd64:main --help
